# Generated by Django 5.2.1 on 2025-05-23 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'column/style',
                'verbose_name_plural': 'columns/styles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4)),
                ('symbol', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublishPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'publish period',
                'verbose_name_plural': 'publish periods',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'tracks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='journal_covers/')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('apc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='article-processing charge')),
                ('rating_avg', models.FloatField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('col_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='sijApp.colstyle')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='sijApp.country')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sijApp.currency')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='sijApp.institution')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='sijApp.language')),
                ('publish_period', models.ManyToManyField(blank=True, related_name='journals', to='sijApp.publishperiod')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='sijApp.rank')),
                ('track', models.ManyToManyField(blank=True, related_name='journals', to='sijApp.track')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='sijApp_jour_name_0c47fe_idx'), models.Index(fields=['rating_avg'], name='sijApp_jour_rating__5fbe4f_idx')],
            },
        ),
    ]
