# Generated by Django 5.2.1 on 2025-05-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='alpha_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='ISO 4217 alpha code'),
        ),
        migrations.AddField(
            model_name='currency',
            name='numeric_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='ISO 4217 numeric code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
