# Generated by Django 5.2.1 on 2025-05-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijApp', '0002_currency_alpha_code_currency_numeric_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='alpha_code',
            field=models.CharField(max_length=4, unique=True, verbose_name='ISO 4217 alpha code'),
        ),
    ]
