# Generated by Django 5.2.1 on 2025-05-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sijApp', '0003_alter_currency_alpha_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='numeric_code',
        ),
    ]
