# Generated by Django 5.2.1 on 2025-05-23 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijApp', '0004_remove_currency_numeric_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='rating_avg',
            field=models.FloatField(default=0, help_text='Average rating (0 – 5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
