# Generated by Django 5.2.1 on 2025-05-23 16:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijApp', '0005_alter_journal_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average rating (0.00 – 5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
    ]
