# Generated by Django 5.2.1 on 2025-05-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijApp', '0006_alter_journal_rating_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
